typography_spectrum: 0.1589212
color:
  saturation: 0.8965691
  lightness: 0.2220646
  brandStrength: 0.4910394
  brandColors:
    - '#322E2D'
    - '#AFB7C1'
    - '#784539'
    - '#606863'
    - '#D2A251'
  rhythmicContrast: 0.9525487
layout_spectrum: 0.234767
name: Daniela
navigation:
  - name: hol2
    id: 3d490f57-189c-4677-9c58-ce33ad225392
    type: content
title: daniela
description: ux
